<?php
/**
 * Veritrans VT Direct cimb clicks Model Standard
 *
 * @category   Mage
 * @package    vtcimb/info.phtml
 * @author     denny
 * this template is used for redirecting to Veritrans Payment Page 
 */
?>
<form name="veritransform" method="post" action="<?= $this->getData('redirect_url') ?>">
		<br/>
		<img src="<?php echo $this->getSkinUrl('images/logo.gif')?>"/>
		<br/><br/>
		<div style="font-size:1.1em;font-family:Arial, Helvetica, sans-serif;">
			Please be patient, redirecting to Veritrans. Don't refresh your page...
		</div> <br/>
		<img src="<?php echo $this->getSkinUrl('images/loading.gif')?>"/>				
	</div>
</form>
<script type="text/javascript">
     function redirect(){
	document.veritransform.submit();
     }
     window.onload = redirect;
</script>